# _config.yml
remote_theme: "jekyll/aj@lkn.io"
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: StudiLib
description: A study together app for students
author:
  name: Candy
  email: "candy20190715@outlook.com"
minima:
  hide_site_feed_link: true  # `false` or `null` by default
