# _config.yml
remote_theme: "jekyll/minima@1e8a445"
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: StudiLib
description: A study together app for students
author:
  name: Candy
  email: "candy20190715@outlook.com"
minima:
  social_links:
    - title: Github
      icon: github
      url: "https://github.com/grassparker/grassparker.github.io"
    - title: X
      icon: x-twitter
      url: "https://x.com/grassparkour"
